### PR TITLE
App cleaning and bugfix

### PR DESCRIPTION
**Pull request by sbadia**
* Fix bashisms, and update bash-foo syntax
* Switch to systemd
* Fix interface detection
* Update configuration (a bit more secure, tls, ciphers, auth-key, …)
* Update maintainer/URL/email

### CODE REVIEW

**Comment by sbadia** [comment]
@Psycojoker @opi we made some code-review ? or not ?

**Comment by Psycojoker** [comment]
@sbadia I can have a look but tbh I'm not really qualified enough on this subject to make a good code review :/

**Comment by opi** [comment]
For my first quick code review, everything seems fine. Bash scripts (install, upgrade & remove) should be updated with newly available helpers, and this app needs backup/remove scripts too.
I'll dig into more reviews and tests later

**Comment by sbadia** [comment]
Neat, thanks for the review, don't hesitate to put comments and others things to changes. We can maybe fix this application in a first round, and update to new standards in a second round.

I'll do that!

* [ ] Update install, upgrade, remove scripts with new yunohost helpers
* [ ] Added backup/remove scripts

**Comment by Psycojoker** [comment]
@sbadia for me you can start by making thing works before making things better. I think that in the short term a working (and secure) package would be more useful that a well made package, this second part can come later.

**Comment by sbadia** [comment]
Just tested, install and setup works fine. I've an issue with openvpn report page…
```php
<?php if ($_SERVER['REMOTE_ADDR'] == $_SERVER['SERVER_ADDR']): ?>
```
We setup a route for the server itself :smile: so it's doesn't work ^^
I'll take a look, maybe an external call to whatismyip or something like that…
I'll udpdate the doc also!

**Pull request merged**
