### PR TITLE
Public ip4

### PR DESCRIPTION
**Pull request by zamentur**
This branch prepare a new version for this package with:

- new question allowing to define ip ranges (it could be public ip ranges, so it should be compatible with internetcube)
- backup/restore feature (this feature keeps potential user change)
- usage of ynh helpers
- usage of experimental helpers
- refactoring of code
- support of automated test (see ci-apps.yunohost.org)
- improvement on quality (dependencies management, j2 template, user and permissions)

### CODE REVIEW

**Comment by zamentur** [comment]
Don't merge for the moment, I need to do some tests...

**Comment by zamentur** [comment]
I have tested install upgrade and remove. It works.
I merge to be able to run in ci

**Comment by lapineige** [comment]
Do you want me to test it right now, or should I wait for a more advanced update ?

**Comment by zamentur** [comment]
I will work on it (for backup/restore)
But you can test other scripts if you want

**Comment by zamentur** [comment]
Here is how I test on client side. You need to get the conf on the url of the app. 
apt-get install openvpn
groupadd openvpn
useradd -g openvpn openvpn
cp DOMAIN.conf /etc/openvpn/
touch /etc/openvpn/auth.txt
chmod go=--- /etc/openvpn/auth.txt
echo "USER\nPASS" > /etc/openvpn/auth.txt
edit /etc/hosts
openvpn --config DOMAIN.conf

**Comment by lapineige** [comment]
I have it already installed and working. Should I just test your upgrade script and see if it's still working ?

**Pull request merged**
